
# Robot Configuration

# Check for lidar and camera extrinsics files in two places with following priorities:
#  1.) in ~/.ros/extrinsics/<SENSOR>_extrinsics_<POSITION>.yaml
#  2.) in package magni_description/extrinsics/<SENSOR>_extrinsics_<POSITION>.yaml
# where <SENSOR> is either "camera" or "lidar" and <POSITION> is an arbitrary string with which the extrinsics file is identified
raspicam_position: 'forward' # to disable insert "None"
lidar_position : 'top_plate'  # to disable insert "None"

sonars: None
# sonars: 'pi_sonar_v1' # Use this to enable sonars

force_time_sync : 'True'
oled_display_controller: None

motor_controller_board_version : None 
motor_controller_serial_port: '/dev/ttyAMA0'
motor_controller_serial_baud: 38400
motor_controller_pid_proportional: 5000
motor_controller_pid_integral: 7
motor_controller_pid_derivative: -110
motor_controller_pid_denominator: 1000
motor_controller_pid_moving_buffer_size: 70
motor_controller_pid_velocity: 15000

vel_controller_wheel_separation_multiplier: 1.0 # default: 1.0
vel_controller_wheel_radius_multiplier    : 1.0 # default: 1.0

vel_controller_lin_x_has_velocity_limits    : true
vel_controller_lin_x_max_velocity           : 1.0   # m/s
vel_controller_lin_x_has_acceleration_limits: true
vel_controller_lin_x_max_acceleration       : 1.1   # m/s^2
vel_controller_ang_z_has_velocity_limits    : true
vel_controller_ang_max_velocity           : 2.0   # rad/s
vel_controller_ang_has_acceleration_limits: true
vel_controller_ang_max_acceleration       : 5.0   # rad/s^2
